config/routes.rb
Rails.application.routes.draw do

  get 'pages/index' => 'pages#index'
  resources :medi_sessions
  delete '/logout', to: 'sessions#destroy'
  get '/auth/:provider/callback', to: 'sessions#create'
  get '/auth/failure', to: 'sessions#auth_failure'

  root 'medi_sessions#index'

end

app/models/medi_session.rb
class MediSession < ActiveRecord::Base
    has_many :user_sessions
    has_many :users, through: :user_sessions
end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :user_sessions
  has_many :medi_sessions, through: :user_sessions


  class << self
    def from_omniauth(auth_hash)
      user = find_or_create_by(uid: auth_hash['uid'], provider: auth_hash['provider'])
      user.name = auth_hash['info']['name']
      user.location = get_social_location_for user.provider, auth_hash['info']['location']
      user.image_url = auth_hash['info']['image']
      user.url = get_social_url_for user.provider, auth_hash['info']['urls']
      user.save!
      user
    end

    private

    def get_social_location_for(provider, location_hash)
      case provider
        when 'linkedin'
          location_hash['name']
        else
          location_hash
      end
    end

    def get_social_url_for(provider, urls_hash)
      case provider
        when 'linkedin'
          urls_hash['public_profile']
        else
          urls_hash[provider.capitalize]
      end
    end
  end


end

app/models/user_session.rb
class UserSession < ActiveRecord::Base
    belongs_to :user
    belongs_to :medi_session
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  helper_method :current_user
end

app/controllers/medi_sessions_controller.rb
class MediSessionsController < ApplicationController
  before_action :set_medi_session, only: [:show, :edit, :update, :destroy]

  # GET /medi_sessions
  # GET /medi_sessions.json
  def index
    @medi_sessions = MediSession.all
    @medi_session = MediSession.new

  end

  # GET /medi_sessions/1
  # GET /medi_sessions/1.json
  def show
  end

  # GET /medi_sessions/new
  def new
    @medi_session = MediSession.new
  end

  # GET /medi_sessions/1/edit
  def edit
  end

  # POST /medi_sessions
  # POST /medi_sessions.json
  def create

      @medi_session = MediSession.new(medi_session_params)

      respond_to do |format|
        if @medi_session.save
          format.html { redirect_to root_path, notice: 'Medi session was successfully created.' }
          format.json { render :show, status: :created, location: @medi_session }
        else
          format.html { render :new }
          format.json { render json: @medi_session.errors, status: :unprocessable_entity }
        end
      end
  end

  # PATCH/PUT /medi_sessions/1
  # PATCH/PUT /medi_sessions/1.json
  def update
    respond_to do |format|
      if @medi_session.update(medi_session_params)
        format.html { redirect_to @medi_session, notice: 'Medi session was successfully updated.' }
        format.json { render :show, status: :ok, location: @medi_session }
      else
        format.html { render :edit }
        format.json { render json: @medi_session.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /medi_sessions/1
  # DELETE /medi_sessions/1.json
  def destroy
    @medi_session.destroy
    respond_to do |format|
      format.html { redirect_to medi_sessions_url, notice: 'Medi session was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_medi_session
      @medi_session = MediSession.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def medi_session_params
      params.require(:medi_session).permit(:private, :time_start, :time_end)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    #render text: request.env['omniauth.auth'].to_yaml and return
    begin
      @user = User.from_omniauth(request.env['omniauth.auth'])
      session[:user_id] = @user.id
      flash[:success] = "Welcome, #{@user.name}!"
    rescue
     flash[:warning] = "There was an error while trying to authenticate you..."
    end
    redirect_to root_path
  end

  def destroy
    if current_user
      session.delete(:user_id)
      flash[:success] = 'See you!'
    end
    redirect_to root_path
  end

  def auth_failure
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/medi_sessions_helper.rb
module MediSessionsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Yurt of Happines</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-inverse">
  <div class="container">
    <div class="navbar-header">
      <%= link_to 'Yurt-O-Happiness', root_path, class: 'navbar-brand' %>
    </div>
      <!-- Small modal -->
      <button type="button" class="btn btn-primary" data-toggle="modal" data-target=".bs-example-modal-sm">Start A Session</button>
      <div class="modal fade bs-example-modal-sm" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel">
        <div class="modal-dialog modal-sm">
          <div class="modal-content">
            <%= render 'form' %>
          </div>
        </div>
      </div>

    <div id="navbar">
      <% if current_user %>
        <ul class="nav navbar-nav pull-right">
          <li><%= image_tag current_user.image_url, alt: current_user.name %></li>
          <li><%= link_to 'Log Out', logout_path, method: :delete %></li>
        </ul>
      <% else %>
        <ul class="nav navbar-nav">
          <li><%= link_to 'Google+', '/auth/google' %></li>
        </ul>
      <% end %>
    </div>
  </div>
</nav>

<div class="container">
  <% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>">
      <%= value %>
    </div>
  <% end %>

  <%= yield %>
</div>

</body>
</html>

app/views/medi_sessions/_form.html.erb
<% if current_user  %>

  <%= form_for(@medi_session) do |f| %>
    <% if @medi_session.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@medi_session.errors.count, "error") %> prohibited this medi_session from being saved:</h2>

        <ul>
        <% @medi_session.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.label :private %><br>
      <%= f.check_box :private %>
    </div>
    <div class="field">
      <%= f.label :time_start %><br>
      <%= f.datetime_select :time_start %>
    </div>
    <div class="field">
      <%= f.label :time_end %><br>
      <%= f.datetime_select :time_end %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>

  <% else %>

    <div> Please login! </div>

  <% end %>

app/views/medi_sessions/edit.html.erb
<h1>Editing Medi Session</h1>

<%= render 'form' %>

<%= link_to 'Show', @medi_session %> |
<%= link_to 'Back', medi_sessions_path %>

app/views/medi_sessions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Medi Sessions</h1>

<table>
  <thead>
    <tr>
      <th>Private</th>
      <th>Time start</th>
      <th>Time end</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @medi_sessions.each do |medi_session| %>
      <tr>
        <td><%= medi_session.private %></td>
        <td><%= medi_session.time_start %></td>
        <td><%= medi_session.time_end %>|</td>
        <td><%= link_to 'Show', medi_session %>|</td>
        <td><%= link_to 'Edit', edit_medi_session_path(medi_session) %>|</td>
        <td><%= link_to 'X', medi_session, method: :delete, data: { confirm: 'Are you sure?' } %>|</td>
        <td><%= link_to 'Join' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/medi_sessions/new.html.erb
<h1>New Medi Session</h1>

<%= render 'form' %>

<%= link_to 'Back', medi_sessions_path %>

app/views/medi_sessions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Private:</strong>
  <%= @medi_session.private %>
</p>

<p>
  <strong>Time start:</strong>
  <%= @medi_session.time_start %>
</p>

<p>
  <strong>Time end:</strong>
  <%= @medi_session.time_end %>
</p>

<%= link_to 'Edit', edit_medi_session_path(@medi_session) %> |
<%= link_to 'Back', medi_sessions_path %>

app/views/pages/_welcome.html.erb
<div class="jumbotron">
  <h1>Welcome!</h1>
  <p>Authenticate via one of the social networks to get started.</p>
</div>

app/views/pages/index.html.erb
<% if current_user %>
  <div class="page-header">
    <h1>Here is some info about you...</h1>
  </div>
  <div class="panel panel-default">
    <div class="panel-body">
      <ul>
        <li><strong>Name:</strong> <%= current_user.name %></li>
        <li><strong>Provider:</strong> <%= current_user.provider %></li>
        <li><strong>Avatar:</strong> <%= image_tag current_user.image_url %></li>
        <li><strong>URL:</strong> <%= link_to 'google +', current_user.url %></li>
      </ul>
    </div>
  </div>
<% else %>
  <%= render 'welcome' %>
<% end %>